name: Node.js Package

on:
  release:
    types: [created]
  push:
    #分支可以选择多个，如：master、main、release
    #监听main分支的push操作，只要main分支发生push操作，即会运行发布代码
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 获取源码
        uses: actions/checkout@v3
      - name: Node环境版本
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: 安装依赖
        run: npm install
      - name: 发布
        run: npm publish
        env:
          # 通过NPM_TOKEN，Github Action才可以直接发布
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}